FROM node:15.14


USER node
ENV HOME /home/node
RUN mkdir $HOME/app
WORKDIR $HOME/app
# RUN curl -o- -L https://yarnpkg.com/install.sh | /bin/sh && npm install -g create-react-app && npm install --save react react-dom && npm install --save-dev @types/react-dom @types/webpack @types/webpack-dev-server ts-loader ts-node typescript webpack webpack-cli webpack-dev-server

